
server_name: 172.31.105.123
network_name: esnet


elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
elasticsearch_hostname: es01
elasticsearch_conf_dir: /usr/share/elasticsearch

kibana_image: docker.elastic.co/kibana/kibana:7.10.1
kibana_hostname: ki01

logstash_image: docker.elastic.co/logstash/logstash:7.10.1
logstash_hostname: lo01
logstash_conf_dir: /usr/share/logstash

elastic_password: "TZdufKDLQbkUZSuzaO1S"
kibana_password: "cfVySe7jGUCijYdJ1TWj"
